### ISSUE TITLE
compile failed occasionally when do parallel build

### ISSUE THREAD

**Issue by sandy-lcq** [troglobit/sysklogd#11]
I build sysklogd under yocto project,   and  compiled with "make -j 10"
and sometimes, compile failed with error:

DEBUG: Executing python function autotools_aclocals
DEBUG: SITE files ['endian-little', 'bit-64', 'arm-common', 'arm-64', 'common-linux', 'common-glibc', 'aarch64-linux', 'common']
DEBUG: Python function autotools_aclocals finished
DEBUG: Executing shell function do_compile
NOTE: make -j 10
make  all-recursive
make[1]: Entering directory 'TOPDIR/tmp-glibc/work/aarch64-wrs-linux/sysklogd/2.0.3-r0/build'
Making all in example
make[2]: Entering directory 'TOPDIR/tmp-glibc/work/aarch64-wrs-linux/sysklogd/2.0.3-r0/build/example'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory 'TOPDIR/tmp-glibc/work/aarch64-wrs-linux/sysklogd/2.0.3-r0/build/example'
Making all in man
make[2]: Entering directory 'TOPDIR/tmp-glibc/work/aarch64-wrs-linux/sysklogd/2.0.3-r0/build/man'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory 'TOPDIR/tmp-glibc/work/aarch64-wrs-linux/sysklogd/2.0.3-r0/build/man'
Making all in src
make[2]: Entering directory 'TOPDIR/tmp-glibc/work/aarch64-wrs-linux/sysklogd/2.0.3-r0/build/src'
ccache aarch64-wrs-linux-gcc  -march=armv8-a+crc -no-pie -fno-PIE --sysroot=TOPDIR/tmp-glibc/work/aarch64-wrs-linux/sysklogd/2.0.3-r0/recipe-sysroot -DHAVE_CONFIG_H -I. -I../../git/src -I..  -DSYSCONFDIR=\"/etc\" -DRUNSTATEDIR=\"/var/run\" -D_BSD_SOURCE -D_DEFAULT_SOURCE -D_XOPEN_SOURCE=600  -W -Wall -Wextra -Wno-unused-result -Wno-unused-parameter -fno-strict-aliasing -O2 -pipe -g -feliminate-unused-debug-types -fmacro-prefix-map=TOPDIR/tmp-glibc/work/aarch64-wrs-linux/sysklogd/2.0.3-r0=/usr/src/debug/sysklogd/2.0.3-r0                      -fdebug-prefix-map=TOPDIR/tmp-glibc/work/aarch64-wrs-linux/sysklogd/2.0.3-r0=/usr/src/debug/sysklogd/2.0.3-r0                      -fdebug-prefix-map=TOPDIR/tmp-glibc/work/aarch64-wrs-linux/sysklogd/2.0.3-r0/recipe-sysroot=                      -fdebug-prefix-map=TOPDIR/tmp-glibc/work/aarch64-wrs-linux/sysklogd/2.0.3-r0/recipe-sysroot-native=  -c -o syslogd-syslogd.o `test -f 'syslogd.c' || echo '../../git/src/'`syslogd.c
ccache aarch64-wrs-linux-gcc  -march=armv8-a+crc -no-pie -fno-PIE --sysroot=TOPDIR/tmp-glibc/work/aarch64-wrs-linux/sysklogd/2.0.3-r0/recipe-sysroot -DHAVE_CONFIG_H -I. -I../../git/src -I..  -DSYSCONFDIR=\"/etc\" -DRUNSTATEDIR=\"/var/run\" -D_BSD_SOURCE -D_DEFAULT_SOURCE -D_XOPEN_SOURCE=600  -W -Wall -Wextra -Wno-unused-result -Wno-unused-parameter -fno-strict-aliasing -O2 -pipe -g -feliminate-unused-debug-types -fmacro-prefix-map=TOPDIR/tmp-glibc/work/aarch64-wrs-linux/sysklogd/2.0.3-r0=/usr/src/debug/sysklogd/2.0.3-r0                      -fdebug-prefix-map=TOPDIR/tmp-glibc/work/aarch64-wrs-linux/sysklogd/2.0.3-r0=/usr/src/debug/sysklogd/2.0.3-r0                      -fdebug-prefix-map=TOPDIR/tmp-glibc/work/aarch64-wrs-linux/sysklogd/2.0.3-r0/recipe-sysroot=                      -fdebug-prefix-map=TOPDIR/tmp-glibc/work/aarch64-wrs-linux/sysklogd/2.0.3-r0/recipe-sysroot-native=  -c -o syslogd-socket.o `test -f 'socket.c' || echo '../../git/src/'`socket.c
ccache aarch64-wrs-linux-gcc  -march=armv8-a+crc -no-pie -fno-PIE --sysroot=TOPDIR/tmp-glibc/work/aarch64-wrs-linux/sysklogd/2.0.3-r0/recipe-sysroot -DHAVE_CONFIG_H -I. -I../../git/src -I..  -DSYSCONFDIR=\"/etc\" -DRUNSTATEDIR=\"/var/run\" -D_BSD_SOURCE -D_DEFAULT_SOURCE  -W -Wall -Wextra -Wno-unused-result -Wno-unused-parameter -fno-strict-aliasing -O2 -pipe -g -feliminate-unused-debug-types -fmacro-prefix-map=TOPDIR/tmp-glibc/work/aarch64-wrs-linux/sysklogd/2.0.3-r0=/usr/src/debug/sysklogd/2.0.3-r0                      -fdebug-prefix-map=TOPDIR/tmp-glibc/work/aarch64-wrs-linux/sysklogd/2.0.3-r0=/usr/src/debug/sysklogd/2.0.3-r0                      -fdebug-prefix-map=TOPDIR/tmp-glibc/work/aarch64-wrs-linux/sysklogd/2.0.3-r0/recipe-sysroot=                      -fdebug-prefix-map=TOPDIR/tmp-glibc/work/aarch64-wrs-linux/sysklogd/2.0.3-r0/recipe-sysroot-native=  -c -o klogd-klogd.o `test -f 'klogd.c' || echo '../../git/src/'`klogd.c
ccache aarch64-wrs-linux-gcc  -march=armv8-a+crc -no-pie -fno-PIE --sysroot=TOPDIR/tmp-glibc/work/aarch64-wrs-linux/sysklogd/2.0.3-r0/recipe-sysroot -DHAVE_CONFIG_H -I. -I../../git/src -I..  -DSYSCONFDIR=\"/etc\" -DRUNSTATEDIR=\"/var/run\" -D_BSD_SOURCE -D_DEFAULT_SOURCE  -W -Wall -Wextra -Wno-unused-result -Wno-unused-parameter -fno-strict-aliasing -O2 -pipe -g -feliminate-unused-debug-types -fmacro-prefix-map=TOPDIR/tmp-glibc/work/aarch64-wrs-linux/sysklogd/2.0.3-r0=/usr/src/debug/sysklogd/2.0.3-r0                      -fdebug-prefix-map=TOPDIR/tmp-glibc/work/aarch64-wrs-linux/sysklogd/2.0.3-r0=/usr/src/debug/sysklogd/2.0.3-r0                      -fdebug-prefix-map=TOPDIR/tmp-glibc/work/aarch64-wrs-linux/sysklogd/2.0.3-r0/recipe-sysroot=                      -fdebug-prefix-map=TOPDIR/tmp-glibc/work/aarch64-wrs-linux/sysklogd/2.0.3-r0/recipe-sysroot-native=  -c -o klogd-ksym.o `test -f 'ksym.c' || echo '../../git/src/'`ksym.c
ccache aarch64-wrs-linux-gcc  -march=armv8-a+crc -no-pie -fno-PIE --sysroot=TOPDIR/tmp-glibc/work/aarch64-wrs-linux/sysklogd/2.0.3-r0/recipe-sysroot -DHAVE_CONFIG_H -I. -I../../git/src -I..  -DSYSCONFDIR=\"/etc\" -DRUNSTATEDIR=\"/var/run\" -D_BSD_SOURCE -D_DEFAULT_SOURCE  -W -Wall -Wextra -Wno-unused-result -Wno-unused-parameter -fno-strict-aliasing -O2 -pipe -g -feliminate-unused-debug-types -fmacro-prefix-map=TOPDIR/tmp-glibc/work/aarch64-wrs-linux/sysklogd/2.0.3-r0=/usr/src/debug/sysklogd/2.0.3-r0                      -fdebug-prefix-map=TOPDIR/tmp-glibc/work/aarch64-wrs-linux/sysklogd/2.0.3-r0=/usr/src/debug/sysklogd/2.0.3-r0                      -fdebug-prefix-map=TOPDIR/tmp-glibc/work/aarch64-wrs-linux/sysklogd/2.0.3-r0/recipe-sysroot=                      -fdebug-prefix-map=TOPDIR/tmp-glibc/work/aarch64-wrs-linux/sysklogd/2.0.3-r0/recipe-sysroot-native=  -c -o klogd-ksym_mod.o `test -f 'ksym_mod.c' || echo '../../git/src/'`ksym_mod.c
../aarch64-wrs-linux-libtool  --tag=CC   --mode=compile ccache aarch64-wrs-linux-gcc  -march=armv8-a+crc -no-pie -fno-PIE --sysroot=TOPDIR/tmp-glibc/work/aarch64-wrs-linux/sysklogd/2.0.3-r0/recipe-sysroot -DHAVE_CONFIG_H -I. -I../../git/src -I..  -DSYSCONFDIR=\"/etc\" -DRUNSTATEDIR=\"/var/run\" -D_BSD_SOURCE -D_DEFAULT_SOURCE -D_XOPEN_SOURCE=600  -W -Wall -Wextra -Wno-unused-result -Wno-unused-parameter -fno-strict-aliasing -O2 -pipe -g -feliminate-unused-debug-types -fmacro-prefix-map=TOPDIR/tmp-glibc/work/aarch64-wrs-linux/sysklogd/2.0.3-r0=/usr/src/debug/sysklogd/2.0.3-r0                      -fdebug-prefix-map=TOPDIR/tmp-glibc/work/aarch64-wrs-linux/sysklogd/2.0.3-r0=/usr/src/debug/sysklogd/2.0.3-r0                      -fdebug-prefix-map=TOPDIR/tmp-glibc/work/aarch64-wrs-linux/sysklogd/2.0.3-r0/recipe-sysroot=                      -fdebug-prefix-map=TOPDIR/tmp-glibc/work/aarch64-wrs-linux/sysklogd/2.0.3-r0/recipe-sysroot-native=  -c -o libsyslog_la-syslog.lo `test -f 'syslog.c' || echo '../../git/src/'`syslog.c
ccache aarch64-wrs-linux-gcc  -march=armv8-a+crc -no-pie -fno-PIE --sysroot=TOPDIR/tmp-glibc/work/aarch64-wrs-linux/sysklogd/2.0.3-r0/recipe-sysroot -DHAVE_CONFIG_H -I. -I../../git/src -I..  -DSYSCONFDIR=\"/etc\" -DRUNSTATEDIR=\"/var/run\" -D_BSD_SOURCE -D_DEFAULT_SOURCE  -W -Wall -Wextra -Wno-unused-result -Wno-unused-parameter -fno-strict-aliasing -O2 -pipe -g -feliminate-unused-debug-types -fmacro-prefix-map=TOPDIR/tmp-glibc/work/aarch64-wrs-linux/sysklogd/2.0.3-r0=/usr/src/debug/sysklogd/2.0.3-r0                      -fdebug-prefix-map=TOPDIR/tmp-glibc/work/aarch64-wrs-linux/sysklogd/2.0.3-r0=/usr/src/debug/sysklogd/2.0.3-r0                      -fdebug-prefix-map=TOPDIR/tmp-glibc/work/aarch64-wrs-linux/sysklogd/2.0.3-r0/recipe-sysroot=                      -fdebug-prefix-map=TOPDIR/tmp-glibc/work/aarch64-wrs-linux/sysklogd/2.0.3-r0/recipe-sysroot-native=  -c -o ../lib/pidfile.o ../../git/src/../lib/pidfile.c
ccache aarch64-wrs-linux-gcc  -march=armv8-a+crc -no-pie -fno-PIE --sysroot=TOPDIR/tmp-glibc/work/aarch64-wrs-linux/sysklogd/2.0.3-r0/recipe-sysroot -DHAVE_CONFIG_H -I. -I../../git/src -I..  -DSYSCONFDIR=\"/etc\" -DRUNSTATEDIR=\"/var/run\" -D_BSD_SOURCE -D_DEFAULT_SOURCE  -W -Wall -Wextra -Wno-unused-result -Wno-unused-parameter -fno-strict-aliasing -O2 -pipe -g -feliminate-unused-debug-types -fmacro-prefix-map=TOPDIR/tmp-glibc/work/aarch64-wrs-linux/sysklogd/2.0.3-r0=/usr/src/debug/sysklogd/2.0.3-r0                      -fdebug-prefix-map=TOPDIR/tmp-glibc/work/aarch64-wrs-linux/sysklogd/2.0.3-r0=/usr/src/debug/sysklogd/2.0.3-r0                      -fdebug-prefix-map=TOPDIR/tmp-glibc/work/aarch64-wrs-linux/sysklogd/2.0.3-r0/recipe-sysroot=                      -fdebug-prefix-map=TOPDIR/tmp-glibc/work/aarch64-wrs-linux/sysklogd/2.0.3-r0/recipe-sysroot-native=  -c -o ../lib/strlcpy.o ../../git/src/../lib/strlcpy.c
ccache aarch64-wrs-linux-gcc  -march=armv8-a+crc -no-pie -fno-PIE --sysroot=TOPDIR/tmp-glibc/work/aarch64-wrs-linux/sysklogd/2.0.3-r0/recipe-sysroot -DHAVE_CONFIG_H -I. -I../../git/src -I..  -DSYSCONFDIR=\"/etc\" -DRUNSTATEDIR=\"/var/run\" -D_BSD_SOURCE -D_DEFAULT_SOURCE  -W -Wall -Wextra -Wno-unused-result -Wno-unused-parameter -fno-strict-aliasing -O2 -pipe -g -feliminate-unused-debug-types -fmacro-prefix-map=TOPDIR/tmp-glibc/work/aarch64-wrs-linux/sysklogd/2.0.3-r0=/usr/src/debug/sysklogd/2.0.3-r0                      -fdebug-prefix-map=TOPDIR/tmp-glibc/work/aarch64-wrs-linux/sysklogd/2.0.3-r0=/usr/src/debug/sysklogd/2.0.3-r0                      -fdebug-prefix-map=TOPDIR/tmp-glibc/work/aarch64-wrs-linux/sysklogd/2.0.3-r0/recipe-sysroot=                      -fdebug-prefix-map=TOPDIR/tmp-glibc/work/aarch64-wrs-linux/sysklogd/2.0.3-r0/recipe-sysroot-native=  -c -o ../lib/strlcat.o ../../git/src/../lib/strlcat.c
../aarch64-wrs-linux-libtool  --tag=CC   --mode=compile ccache aarch64-wrs-linux-gcc  -march=armv8-a+crc -no-pie -fno-PIE --sysroot=TOPDIR/tmp-glibc/work/aarch64-wrs-linux/sysklogd/2.0.3-r0/recipe-sysroot -DHAVE_CONFIG_H -I. -I../../git/src -I..  -DSYSCONFDIR=\"/etc\" -DRUNSTATEDIR=\"/var/run\" -D_BSD_SOURCE -D_DEFAULT_SOURCE  -W -Wall -Wextra -Wno-unused-result -Wno-unused-parameter -fno-strict-aliasing -O2 -pipe -g -feliminate-unused-debug-types -fmacro-prefix-map=TOPDIR/tmp-glibc/work/aarch64-wrs-linux/sysklogd/2.0.3-r0=/usr/src/debug/sysklogd/2.0.3-r0                      -fdebug-prefix-map=TOPDIR/tmp-glibc/work/aarch64-wrs-linux/sysklogd/2.0.3-r0=/usr/src/debug/sysklogd/2.0.3-r0                      -fdebug-prefix-map=TOPDIR/tmp-glibc/work/aarch64-wrs-linux/sysklogd/2.0.3-r0/recipe-sysroot=                      -fdebug-prefix-map=TOPDIR/tmp-glibc/work/aarch64-wrs-linux/sysklogd/2.0.3-r0/recipe-sysroot-native=  -c -o ../lib/strlcpy.lo ../../git/src/../lib/strlcpy.c
aarch64-wrs-linux-libtool: compile:  ccache aarch64-wrs-linux-gcc -march=armv8-a+crc -no-pie -fno-PIE --sysroot=TOPDIR/tmp-glibc/work/aarch64-wrs-linux/sysklogd/2.0.3-r0/recipe-sysroot -DHAVE_CONFIG_H -I. -I../../git/src -I.. -DSYSCONFDIR=\"/etc\" -DRUNSTATEDIR=\"/var/run\" -D_BSD_SOURCE -D_DEFAULT_SOURCE -D_XOPEN_SOURCE=600 -W -Wall -Wextra -Wno-unused-result -Wno-unused-parameter -fno-strict-aliasing -O2 -pipe -g -feliminate-unused-debug-types -fmacro-prefix-map=TOPDIR/tmp-glibc/work/aarch64-wrs-linux/sysklogd/2.0.3-r0=/usr/src/debug/sysklogd/2.0.3-r0 -fdebug-prefix-map=TOPDIR/tmp-glibc/work/aarch64-wrs-linux/sysklogd/2.0.3-r0=/usr/src/debug/sysklogd/2.0.3-r0 -fdebug-prefix-map=TOPDIR/tmp-glibc/work/aarch64-wrs-linux/sysklogd/2.0.3-r0/recipe-sysroot= -fdebug-prefix-map=TOPDIR/tmp-glibc/work/aarch64-wrs-linux/sysklogd/2.0.3-r0/recipe-sysroot-native= -c ../../git/src/syslog.c  -fPIC -DPIC -o .libs/libsyslog_la-syslog.o
aarch64-wrs-linux-libtool: compile:  ccache aarch64-wrs-linux-gcc -march=armv8-a+crc -no-pie -fno-PIE --sysroot=TOPDIR/tmp-glibc/work/aarch64-wrs-linux/sysklogd/2.0.3-r0/recipe-sysroot -DHAVE_CONFIG_H -I. -I../../git/src -I.. -DSYSCONFDIR=\"/etc\" -DRUNSTATEDIR=\"/var/run\" -D_BSD_SOURCE -D_DEFAULT_SOURCE -W -Wall -Wextra -Wno-unused-result -Wno-unused-parameter -fno-strict-aliasing -O2 -pipe -g -feliminate-unused-debug-types -fmacro-prefix-map=TOPDIR/tmp-glibc/work/aarch64-wrs-linux/sysklogd/2.0.3-r0=/usr/src/debug/sysklogd/2.0.3-r0 -fdebug-prefix-map=TOPDIR/tmp-glibc/work/aarch64-wrs-linux/sysklogd/2.0.3-r0=/usr/src/debug/sysklogd/2.0.3-r0 -fdebug-prefix-map=TOPDIR/tmp-glibc/work/aarch64-wrs-linux/sysklogd/2.0.3-r0/recipe-sysroot= -fdebug-prefix-map=TOPDIR/tmp-glibc/work/aarch64-wrs-linux/sysklogd/2.0.3-r0/recipe-sysroot-native= -c ../../git/src/../lib/strlcpy.c  -fPIC -DPIC -o ../lib/.libs/strlcpy.o
../aarch64-wrs-linux-libtool  --tag=CC   --mode=compile ccache aarch64-wrs-linux-gcc  -march=armv8-a+crc -no-pie -fno-PIE --sysroot=TOPDIR/tmp-glibc/work/aarch64-wrs-linux/sysklogd/2.0.3-r0/recipe-sysroot -DHAVE_CONFIG_H -I. -I../../git/src -I..  -DSYSCONFDIR=\"/etc\" -DRUNSTATEDIR=\"/var/run\" -D_BSD_SOURCE -D_DEFAULT_SOURCE  -W -Wall -Wextra -Wno-unused-result -Wno-unused-parameter -fno-strict-aliasing -O2 -pipe -g -feliminate-unused-debug-types -fmacro-prefix-map=TOPDIR/tmp-glibc/work/aarch64-wrs-linux/sysklogd/2.0.3-r0=/usr/src/debug/sysklogd/2.0.3-r0                      -fdebug-prefix-map=TOPDIR/tmp-glibc/work/aarch64-wrs-linux/sysklogd/2.0.3-r0=/usr/src/debug/sysklogd/2.0.3-r0                      -fdebug-prefix-map=TOPDIR/tmp-glibc/work/aarch64-wrs-linux/sysklogd/2.0.3-r0/recipe-sysroot=                      -fdebug-prefix-map=TOPDIR/tmp-glibc/work/aarch64-wrs-linux/sysklogd/2.0.3-r0/recipe-sysroot-native=  -c -o ../lib/strlcat.lo ../../git/src/../lib/strlcat.c
aarch64-wrs-linux-libtool: compile:  ccache aarch64-wrs-linux-gcc -march=armv8-a+crc -no-pie -fno-PIE --sysroot=TOPDIR/tmp-glibc/work/aarch64-wrs-linux/sysklogd/2.0.3-r0/recipe-sysroot -DHAVE_CONFIG_H -I. -I../../git/src -I.. -DSYSCONFDIR=\"/etc\" -DRUNSTATEDIR=\"/var/run\" -D_BSD_SOURCE -D_DEFAULT_SOURCE -W -Wall -Wextra -Wno-unused-result -Wno-unused-parameter -fno-strict-aliasing -O2 -pipe -g -feliminate-unused-debug-types -fmacro-prefix-map=TOPDIR/tmp-glibc/work/aarch64-wrs-linux/sysklogd/2.0.3-r0=/usr/src/debug/sysklogd/2.0.3-r0 -fdebug-prefix-map=TOPDIR/tmp-glibc/work/aarch64-wrs-linux/sysklogd/2.0.3-r0=/usr/src/debug/sysklogd/2.0.3-r0 -fdebug-prefix-map=TOPDIR/tmp-glibc/work/aarch64-wrs-linux/sysklogd/2.0.3-r0/recipe-sysroot= -fdebug-prefix-map=TOPDIR/tmp-glibc/work/aarch64-wrs-linux/sysklogd/2.0.3-r0/recipe-sysroot-native= -c ../../git/src/../lib/strlcat.c  -fPIC -DPIC -o ../lib/.libs/strlcat.o
../aarch64-wrs-linux-libtool  --tag=CC   --mode=link ccache aarch64-wrs-linux-gcc  -march=armv8-a+crc -no-pie -fno-PIE --sysroot=TOPDIR/tmp-glibc/work/aarch64-wrs-linux/sysklogd/2.0.3-r0/recipe-sysroot -W -Wall -Wextra -Wno-unused-result -Wno-unused-parameter -fno-strict-aliasing -O2 -pipe -g -feliminate-unused-debug-types -fmacro-prefix-map=TOPDIR/tmp-glibc/work/aarch64-wrs-linux/sysklogd/2.0.3-r0=/usr/src/debug/sysklogd/2.0.3-r0                      -fdebug-prefix-map=TOPDIR/tmp-glibc/work/aarch64-wrs-linux/sysklogd/2.0.3-r0=/usr/src/debug/sysklogd/2.0.3-r0                      -fdebug-prefix-map=TOPDIR/tmp-glibc/work/aarch64-wrs-linux/sysklogd/2.0.3-r0/recipe-sysroot=                      -fdebug-prefix-map=TOPDIR/tmp-glibc/work/aarch64-wrs-linux/sysklogd/2.0.3-r0/recipe-sysroot-native=   -Wl,-O1 -Wl,--hash-style=gnu -Wl,--as-needed  -o syslogd syslogd-syslogd.o syslogd-socket.o  ../lib/pidfile.o ../lib/strlcpy.o ../lib/strlcat.o 
aarch64-wrs-linux-libtool: link: ccache aarch64-wrs-linux-gcc -march=armv8-a+crc -no-pie -fno-PIE --sysroot=TOPDIR/tmp-glibc/work/aarch64-wrs-linux/sysklogd/2.0.3-r0/recipe-sysroot -W -Wall -Wextra -Wno-unused-result -Wno-unused-parameter -fno-strict-aliasing -O2 -pipe -g -feliminate-unused-debug-types -fmacro-prefix-map=TOPDIR/tmp-glibc/work/aarch64-wrs-linux/sysklogd/2.0.3-r0=/usr/src/debug/sysklogd/2.0.3-r0 -fdebug-prefix-map=TOPDIR/tmp-glibc/work/aarch64-wrs-linux/sysklogd/2.0.3-r0=/usr/src/debug/sysklogd/2.0.3-r0 -fdebug-prefix-map=TOPDIR/tmp-glibc/work/aarch64-wrs-linux/sysklogd/2.0.3-r0/recipe-sysroot= -fdebug-prefix-map=TOPDIR/tmp-glibc/work/aarch64-wrs-linux/sysklogd/2.0.3-r0/recipe-sysroot-native= -Wl,-O1 -Wl,--hash-style=gnu -Wl,--as-needed -o syslogd syslogd-syslogd.o syslogd-socket.o ../lib/pidfile.o ../lib/strlcpy.o ../lib/strlcat.o 
aarch64-wrs-linux-gcc: error: ../lib/strlcat.o: No such file or directory
make[2]: *** [Makefile:620: syslogd] Error 1
make[2]: *** Waiting for unfinished jobs....
aarch64-wrs-linux-libtool: compile:  ccache aarch64-wrs-linux-gcc -march=armv8-a+crc -no-pie -fno-PIE --sysroot=TOPDIR/tmp-glibc/work/aarch64-wrs-linux/sysklogd/2.0.3-r0/recipe-sysroot -DHAVE_CONFIG

But I checked after compile stopped,  strlcat.o existed,  so I suspects there is parallel race condition,  but I checked line 620 in Makefile,  seems strlcat.o already in sysklogd's dependency,
Could you help to see what maybe the problem? Thanks

**Comment by troglobit** [comment]
Hi, yes this is a dependency bug. Both $DAJOB and Gentoo found this earlier, and it is fixed in 9cf1f97, not yet released though since v2.1 is waiting for a Coverity Scan run.

(Also, FYI, v2.1 has removed klogd entirely in favor of native support in syslogd to read the kernel logs)

**Comment by sandy-lcq** [comment]
@troglobit I can still reproduce this problem with patch 9cf1f97,  do we still need .NOTPARALLEL in Makefile under src?

**Comment by troglobit** [comment]
Just got a report about this over IRC for CRUX Linux. I'm reopening this issue and will start looking at it later today.  We have some rather crazy quick build servers at work I can use to try and reproduce it.  

I'm not overly happy with the current .NOTPARALLEL fix, so I'll probably have a look at redoing the build deps. instead.

**Comment by troglobit** [comment]
@sandy-lcq Here's a refactor; 84d70e6 removes the local/helper lib libcompat.la.  If you can, please help test this.

**Comment by sandy-lcq** [comment]
OK
